// questionTypes
export const GET_QUESTION = "GET_QUESTION";
export const CLEAR_QUESTION = "CLEAR_QUESTION";

// amountTypes
export const INCREASE_AMOUNT = "INCREASE_AMOUNT";
export const RESET_AMOUNT = "RESET_AMOUNT";

// dialTypes
export const SET_POSITION = "SET_POSITION";
export const SET_CURRENT_MAXANGLE = "SET_CURRENT_MAXANGLE";

// choiceTypes
export const SET_CHOICE = "SET_CHOICE";
export const RESET_CHOICE = "RESET_CHOICE";

// selectionTypes
export const ADD_SELECTION = "ADD_SELECTION";
export const UPDATE_SELECTION = "UPDATE_SELECTION";
export const REMOVE_SELECTION = "REMOVE_SELECTION";

// resultTypes
export const GET_RESULT = "GET_RESULT";
export const CLEAR_RESULT = "CLEAR_RESULT";

// uiTypes
export const SCREEN_RESIZE = "SCREEN_RESIZE";

// dispensaryTypes
export const GET_DISPENSARY = "GET_DISPENSARY";
export const GET_DISPENSARY_BY_ACCOUNT = "GET_DISPENSARY_BY_ACCOUNT";

// ageVerificationTypes
export const RECORD_AGEVERIFICATION = "RECORD_AGEVERIFICATION";
export const INIT_AGEVERIFICATION = "INIT_AGEVERIFICATION";

// terms of use types
export const INIT_TERMS_RESPONSE = "INIT_TERMS_RESPONSE";
export const RECORD_TERMS_RESPONSE = "RECORD_TERMS_RESPONSE";

// geo loc types
export const GET_GEOLOCATION = "GET_GEOLOCATION";
export const INIT_GEOLOCATION = "INIT_GEOLOCATION";
export const SET_GEOLOADING = "SET_GEOLOADING";
export const GEOERROR = "GEOERROR";
export const GEO_BROWSERSUPPORTED = "GEO_BROWSERSUPPORTED";

// user types
export const GET_USER = "GET_USER";
export const GET_USER_BY_TOKEN = "GET_USER_BY_TOKEN";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const SET_PASSWORD = "SET_PASSWORD";
export const GET_USER_WITH_ACCOUNTS = "GET_USER_WITH_ACCOUNTS";
export const FULL_LOGIN = "FULL_LOGIN";
export const LOGOUT = "LOGOUT";
export const CHECK_SESSION = "CHECK_SESSION";
export const UPDATE_USER_SETTINGS = "UPDATE_USER_SETTINGS";
export const SET_NEW_USER_PREFS = "SET_NEW_USER_PREFS";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const RESEND_PENDING_EMAIL = "RESEND_PENDING_EMAIL";

// auth types
export const SUBMIT_LOGIN = "SUBMIT_LOGIN";
export const CREATE_USER = "CREATE_USER";

// admin types
export const GET_MASTER_ACCOUNTS = "GET_MASTER_ACCOUNTS";
export const GET_PENDING_USERS = "GET_PENDING_USERS";
export const CREATE_MASTER_ACCOUNT = "CREATE_MASTER_ACCOUNT";
export const GET_SUPPRESSION_LIST = "GET_SUPPRESSION_LIST";
export const DELETE_SUPPRESSION = "DELETE_SUPPRESSION";
export const ADMIN_GET_USER = "ADMIN_GET_USER";
export const ADMIN_DELETE_USER = "ADMIN_DELETE_USER";

// account types
export const CHANGE_DISPENSARY_LOGO = "CHANGE_DISPENSARY_LOGO";
export const CHANGE_DISPENSARY_ADDRESS = "CHANGE_DISPENSARY_ADDRESS";
export const CHECK_DISPENSARY_ADDRESS = "CHECK_DISPENSARY_ADDRESS";
export const GET_USERS_BY_ACCOUNT = "GET_USERS_BY_ACCOUNT";
export const GET_PENDING_USERS_BY_ACCOUNT = "GET_PENDING_USERS_BY_ACCOUNT";
export const CREATE_DISPENSARY_ADDRESS = "CREATE_DISPENSARY_ADDRESS";
export const DELETE_DISPENSARY_ADDRESS = "DELETE_DISPENSARY_ADDRESS";
export const CHANGE_MASTER_NAME = "CHANGE_MASTER_NAME";
export const ADD_USER_TO_MASTER = "ADD_USER_TO_MASTER";
export const ADD_USER_TO_DISPENSARY = "ADD_USER_TO_DISPENSARY";
export const DELETE_USER_FROM_MASTER = "DELETE_USER_FROM_MASTER";
export const DELETE_USER_FROM_DISPENSARY = "DELETE_USER_FROM_DISPENSARY";
export const GET_CUSTOM_STRAINS = "GET_CUSTOM_STRAINS";
export const ADD_CUSTOM_STRAIN = "ADD_CUSTOM_STRAIN";
export const DELETE_CUSTOM_STRAIN = "DELETE_CUSTOM_STRAIN";
export const GET_MASTER_BY_ACCOUNT_ID = "GET_MASTER_BY_ACCOUNT_ID";
export const GET_DISPENSARY_ACCOUNT_BY_ID = "GET_DISPENSARY_ACCOUNT_BY_ID";
